version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule: {interval: weekly}
    groups:
      actions:
        patterns: ["actions/*"]
  - package-ecosystem: gomod
    directory: /writer/native-go
    schedule: {interval: monthly}
